spring.application.name=testando-ideias

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sua-url-de-autorizacao.com

# Endereço do(s) servidor(es) Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Configurações do Produtor (quem envia mensagens)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Configurações do Consumidor (quem lê mensagens)
spring.kafka.consumer.group-id=webhook-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer